language: python
sudo: false
python:
  - "2.7"

branches:
  only:
    - master
    - develop
    - /^feature.*$/

install: "pip install -r requirements.txt && pip install -r test-requirements.txt"

# command to run tests
script: nosetests -w ./test

notifications:
  email: false


